hide-item:
  enabled: '&bPlayers &7(&aShown&7)'
  disabled: '&bPlayers &7(&cHidden&7)'
chat-format: '%vault_prefix%<PLAYER>%vault_suffix% &8» &f<MESSAGE>'
tags:
  empty: '&cNo Tags'
messages:
  join: '%vault_prefix%%player_name%%vault_suffix% &ehopped into the lobby!'
  leave: '%vault_prefix%%player_name%%vault_suffix% &ehopped out of the lobby!'
gui:
  smiley:
    name: "GUI"
    # Make sure the layout's size is a multiple of 9
    layout: [
        "x", "x", "l", "x", "x", "x", "l", "x", "x",
        "x", "x", "l", "x", "x", "x", "l", "x", "x",
        "x", "x", "x", "x", "l", "x", "x", "x", "x",
        "l", "x", "x", "x", "l", "l", "x", "x", "l",
        "x", "l", "x", "x", "x", "x", "x", "l", "x",
        "x", "x", "l", "x", "x", "x", "l", "x", "x"
    ]
    items:
      x:
        name: "STAINED_GLASS_PANE:4"
        executor: "console"
        commands:
          - "tell %player% Smile!"
      l:
        name: "STAINED_GLASS_PANE:7"

  hub:
    name: "GUI"
    # Make sure the layout's size is a multiple of 9
    layout: [
        "x", "x", "l", "x", "x", "x", "l", "x", "x",
        "x", "x", "l", "x", "x", "x", "l", "x", "x",
        "x", "x", "x", "x", "l", "x", "x", "x", "x",
        "l", "x", "x", "x", "l", "l", "x", "x", "l",
        "x", "l", "x", "x", "x", "x", "x", "l", "x",
        "x", "x", "l", "x", "x", "x", "l", "x", "x"
    ]
    items:
      x:
        name: "STAINED_GLASS_PANE:4"
        executor: "console"
        commands:
          - "tell %player% Smile!"
      l:
        name: "STAINED_GLASS_PANE:7"