hide-item:
  enabled: '&bPlayers &7(&aShown&7)'
  disabled: '&bPlayers &7(&cHidden&7)'
chat-format: '%vault_prefix%<PLAYER>%vault_suffix% &8» &f<MESSAGE>'
tags:
  empty: '&cNo Tags'
messages:
  join: '%vault_prefix%%player_name%%vault_suffix% &ehopped into the lobby!'
  leave: '%vault_prefix%%player_name%%vault_suffix% &ehopped out of the lobby!'
gui:
  Example1:
    # Haven't found a way to name the gui a special name but have it's core name be there as well, the key is name, so if you wish to change name, change key name
    #name: "Example 1"
    # Make sure the layout's size is a multiple of 9
    layout: [
        "x", "x", "x", "x", "x", "x", "x", "x", "x",
        "x", "x", "x", "x", "x", "x", "x", "x", "x",
        "x", "x", "x", "x", "x", "x", "x", "x", "x"
    ]
    items:
      x:
        name: "STAINED_GLASS_PANE:7"

  Example2:
    # Haven't found a way to name the gui a special name but have it's core name be there as well, the key is name, so if you wish to change name, change key name
    #name: "Example 2"
    # Make sure the layout's size is a multiple of 9
    layout: [
        "l", "l", "l", "l", "l", "l", "l", "l", "l",
        "l", "x", "l", "x", "l", "x", "l", "x", "l",
        "l", "l", "l", "l", "l", "l", "l", "l", "l"
    ]
    items:
      x:
        name: "Grass"
        material: "GRASS"
        executor: "player"
        commands:
          - "bungee:hub"
      l:
        name: ""
        material: "STAINED_GLASS_PANE:7"