name: PhaseCosmetics
version: ${project.version}
main: net.phasemc.phasecosmetics.PhaseCosmetics
commands:
  tags:
    usage: "Usage: /<command>"
    description: A command to change you suffix.
  phasecosmetics:
    usage: "Usage: /<command> <reload>"
    description: A main command for the PhaseCosmetics plugin.
    permission: phasecosmetics.command
    permission-message: You can't use this command
  fly:
    usage: "Usage: /<command>"
    description: A command for toggeling flight.
    permission: cosmetic.fly
    permission-message: You can't use this command
  block:
    usage: "Usage: /<command> <block>"
    description: A command to give a block without item.
    permission: phasecosmetics.block
    permission-message: You can't use this command
permissions:
  cosmetic.chat.color:
    default: op
  cosmetic.fly:
    default: op
  phasecosmetics.command:
    default: op
  phasecosmetics.block:
    default: op
